flows:
  - import-path: "src.monitor:daily_drift_check"
    name: "daily-drift"
    work_queue_name: "default-queue"
    schedule:
      type: CronSchedule
      cron: "0 0 * * *"
      timezone: "UTC"